name: Repository dispatch run

on:
  push

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.tkn}}
          repository: kazu0523/dispatch
          event-type: echo_message
          client-payload: '{"message": "Hello!"}'
