name: Repository dispatch run
on:
  push
jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        # commitメッセージにautotestを含む場合だけjobを実行する。それ以外のときは何もしない
        # 変数を${{}}で囲ってしまうと常にTrueが返されてしまうので注意
        #if: "contains(github.event.head_commit.message, 'autotest')"
        with:
          token: ${{secrets.tkn}}
          repository: kazu0523/dispatch
          event-type: echo_message
          client-payload: '{"message": "${{github.event.head_commit.message}}","commitid":"${{github.sha}}","branch":"${{github.ref}}" }'
  run-console:
    runs-on: ubuntu-latest
    steps:
      - name: Console output
        # 1. commitメッセージにmessageを含む場合だけjobを実行する。それ以外のときは何もしない
        # 変数を${{}}で囲ってしまうと常にTrueが返されてしまうので注意
        # 最初に!をつければNOTにできる
        if: "!contains(github.event.head_commit.message, 'test message')"
        run: sleep 1ｓ && echo ${{ github.event.head_commit.message }}
        shell: bash
  run-env:
    runs-on: ubuntu-latest
    steps:
      - name: env test 
        run: echo "${{ toJson(github) }}"
  save-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
      - name: Create a Sample File
        run: |
          mkdir -p test/far
          echo "Hello, Aqua!" > test/example.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: test
