name: Repository dispatch run
on:
  push
jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        # 1. commitメッセージにautotestを含む場合だけjobを実行する。それ以外のときは何もしない
        if: contains(${{ github.event.head_commit.message }}, 'autotest') == 1
        with:
          token: ${{secrets.tkn}}
          repository: kazu0523/dispatch
          event-type: echo_message
          client-payload: '{"message": "Hello world!"}'
  run-console:
    runs-on: ubuntu-latest
    steps:
      - name: Console output
        # 1. commitメッセージにmessageを含む場合だけjobを実行する。それ以外のときは何もしない
        if: contains(${{ github.event.head_commit.message }}, 'message') == 1
        run: sleep 15s && echo ${{ github.event.head_commit.message }} && echo contains(${{ github.event.head_commit.message }}, 'message')
        shell: bash
