name: Repository dispatch run
on:
  push
jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        env:
          autotest_check: contains(${{ github.event.head_commit.message }}, 'autotest')
        uses: peter-evans/repository-dispatch@v2
        # 1. commitメッセージにautotestを含む場合だけjobを実行する。それ以外のときは何もしない
        #if: $autotest_check == 1
        with:
          token: ${{secrets.tkn}}
          repository: kazu0523/dispatch
          event-type: echo_message
          client-payload: '{"message": "Hello world!"}'
  run-console:
    runs-on: ubuntu-latest
    steps:
      - name: Console output
        env:
          message_check: contains(${{ github.event.head_commit.message }}, 'message')
        # 1. commitメッセージにmessageを含む場合だけjobを実行する。それ以外のときは何もしない
        run: printenv
        #if: $message_check == 0
        #run: sleep 15s && echo ${{ github.event.head_commit.message }}
        #shell: bash
